### ISSUE TITLE
how to change URL title 

### ISSUE THREAD

**Issue by 54wbvy54** [CinemaPress/CinemaPress#14]
HELLO everyone please help me i can't  find function for change url title i need do translite of title on english words

thanks you

**Comment by 54wbvy54** [comment]
https://example/type/%D1%84%D0%B8%D0%BB%D1%8C%D0%BC%D1%8B

after happens this

**Comment by zeldaroot** [comment]
Hello. Thank you for using CinemaPress.
Dashboard -> URL settings
