### ISSUE TITLE
Option for visitor to add subtitle 

### ISSUE THREAD

**Issue by joe83** [CinemaPress/CinemaPress#17]
Hello, just finished do some customs on this script for my site http://moviesxx1.com/
Is there possible to add some code for the visitor to allow add some subtitle ?

**Comment by zeldaroot** [comment]
Hello. Thank you for using CinemaPress. This is a CMS, the same as WordPress. You add subtitles to your video hosting players. Then these players are inserted into your website. Therefore, please contact your video hosting company on this issue.
