### ISSUE TITLE
Refirect all non-www and www to https and www?

### ISSUE THREAD

**Issue by seve26** [CinemaPress/CinemaPress#20]
Hello after installing Cinemapress, the site url is set like this: `all non www and www` are redirected to `https://example.com`.

I would love to know how to redirect all `non-www` `and www` to `https and www` using Nginx. I'm familiar with apache and htaccess but I'm newbie with ngnix... How to do something like this?

```
example.com -> https://www.example.com
http://example.com -> https://www.example.com
http://www.example.com -> https://www.example.com
www.example.com  -> https://www.example.com
https://example.com > https://www.example.com
```

Thanks a lot
Best Regard

**Comment by zeldaroot** [comment]
Hello.

![image](https://user-images.githubusercontent.com/56031696/136675365-0625271e-d728-4e5d-89d9-31420a72d9a5.png)

1. `HTTPS` - main protocol (by CloudFlare or by `cinemapress https`)
2. `www` - sub-domain
3. `Email and Global Key` CloudFlare - https://dash.cloudflare.com/profile/api-tokens
4.  `Proxied` - for HTTPS by CloudFlare, if you have your own certificate (by `cinemapress https`), then you don't have `Proxied`

Fill in the CloudFlare data first and only then add a subdomain. It will be registered in DNS automatically.

**Comment by seve26** [comment]
Hello,
Thanks a lot for your reply. `HTTPS` was already activated in my site so I setuped the `API CloudFlare` with email and api key then I added `www` in `Domain for users` but when I clic on `Save Changes` I get this error:

![subdomain](https://user-images.githubusercontent.com/1296080/136677803-2e759784-c9d8-43a2-8509-b8d3a4c968c2.jpg)

`NOT «m.», «tv.», «www.», «app.», «ftp.»!`

1) Apparently `www` subdomain are not allowed. What should I do?

2) Regarding SSL, I own a certificat but I don't know where to upload the ssl certificate (ssl-bundle.crt) and the ssl certificate key (domain.key) and what should I modify in the Ngnix configuration file and where to locate this file?

Thanks again!
Best Regards

**Comment by zeldaroot** [comment]
Oops, I'm sorry. I forgot to push.
1. In fact, I looked at the code, and I think there is no point in this restriction, it can be ignored.
2. If you have your own certificate, then do this:
   - First generate **wildcard** certificate `cinemapress https`
   - Now replace the generated certificates from the folders with your certificate files.

`/config/production/nginx/ssl.d/default.conf`
```
ssl_certificate /home/example.com/config/production/nginx/ssl.d/live/example.com/fullchain.pem;
ssl_certificate_key /home/example.com/config/production/nginx/ssl.d/live/example.com/privkey.pem;
ssl_dhparam /home/example.com/config/production/nginx/ssl.d/live/example.com/dhparam.pem;
```
I think you should not replace the certificates with others, since Let's Encrypt provides these certificates for free and with automatic renewal.

**Comment by zeldaroot** [comment]
![image](https://user-images.githubusercontent.com/56031696/136825814-2270b779-18ad-41fb-8931-b012c46c6e60.png)

1. Please use a forward slash `/` in the `path` setting.

**Comment by seve26** [comment]
Sorry to reopen the issue but I would love to know a bit more about installing my own SSL certificate.

> 2. If you have your own certificate, then do this:
>    
>    * First generate **wildcard** certificate `cinemapress https`
>    * Now replace the generated certificates from the folders with your certificate files.
> 
> `/config/production/nginx/ssl.d/default.conf`
> 
> ```
> ssl_certificate /home/example.com/config/production/nginx/ssl.d/live/example.com/fullchain.pem;
> ssl_certificate_key /home/example.com/config/production/nginx/ssl.d/live/example.com/privkey.pem;
> ssl_dhparam /home/example.com/config/production/nginx/ssl.d/live/example.com/dhparam.pem;
> ```

I generated **wildcard** certificate using: `cinemapress https` then I uploaded `www.example.com-bundle.crt` and `www_example_com.key` to:

`/home/example.com/config/production/nginx/ssl.d/live/example.com/ `

![ssl](https://user-images.githubusercontent.com/1296080/137948167-0a6c9b55-868f-492e-996b-bb462011c03d.png)

Then I changed the path in `default.conf` like this:

```
ssl_certificate /home/example.com/config/production/nginx/ssl.d/live/example.com/www.example.com-bundle.crt;
ssl_certificate_key /home/example.com/config/production/nginx/ssl.d/live/example.com/www_example_com.key;
ssl_dhparam /home/example.com/config/production/nginx/ssl.d/live/example.com/dhparam.pem;
```

1) When I try to visit the site, I get Error 521 and after reuploading the original `defaut.conf` the site works again. What did I do wrong?

2) Also regarding `dhparam.pem`, does I need to edit something or replacing it with another file?

3) Using Filetash when I try to go to:

`/home/example.com/config/production/nginx/ssl.d/live/example.com/fullchain.pem;`

and 

`/home/example.com/config/production/nginx/ssl.d/live/example.com/privkey.pem;`

I get `Unknow Path`:

![ooops](https://user-images.githubusercontent.com/1296080/137948245-5391f8d5-048c-424d-99f1-bb7633c9e24d.png)

It seems that `fullchain.pem` and `privkey.pem` doesn't exist, is that normal?

Thanks in advance.
Best Regards
