### ISSUE TITLE
Adds don't appear on the website

### ISSUE THREAD

**Issue by GwamakaCharles** [CinemaPress/CinemaPress#24]
Hello there. I've added cutom ads through the advert module, unfortunately I don't see them on my website. I've also added the ability for the subdomain to change automatically. Could that be the reason?

**Comment by zeldaroot** [comment]
Hello,
It seems to me that the advertising company simply does not buy your ad impressions. Because of this, the code is in the HTML of the website, but there is no advertising in the browser. Please contact the support of the advertising company.

**Comment by zeldaroot** [comment]
> Thanks for the quick response but what do you mean here `Because of this, the code is in the HTML of the website, but there is no advertising in the browser`?

`Ctrl+U`

![image](https://user-images.githubusercontent.com/56031696/137323739-8e15349b-7031-49c1-9ddc-855f4ba5c41a.png)

**Comment by zeldaroot** [comment]
> I've resolved the issue with the ads company. Its because I was using a VPN and they don't show ads for such users.Thank your help.

Well done!
