### ISSUE TITLE
Upgrading Javascript Libraries?

### ISSUE THREAD

**Issue by seve26** [CinemaPress/CinemaPress#26]
Hello, Cinemapress use outdated version of javascript libraries:

[Bootstrap 3.3.4](https://snyk.io/test/npm/bootstrap/3.3.4) (5 vulnerability) and [jQuery 1.9.1](https://snyk.io/test/npm/jquery/1.9.1) (4 vulnerability).

Is it possible to upgrade them to a newest version that fix the vulnerability?

[Bootstrap](https://snyk.io/vuln/npm:bootstrap?lh=3.3.4&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit)
[jQuery](https://snyk.io/vuln/npm:jquery?lh=1.9.1&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit)

Thanks in advance
Best Regards

**Comment by zeldaroot** [comment]
This does not matter at all, since the user does not have authorization or a personal account on the website.
Please just delete the comments `\*! ... *\` with the version information, and the analyzer will not know what this file is.

**Comment by seve26** [comment]
Thank's a lot for answering. Ok I will just delete comments.
Best Regards

**Comment by seve26** [comment]
Finally I switched theme and I'm not facing this issue anymore. :+1: 
Best Regards
