### ISSUE TITLE
How can I build it locally in my laptop?

### ISSUE THREAD

**Issue by rokib-rajon** [CinemaPress/CinemaPress#3]
Hi,
I am really impressed with your work. I want to build a website on my laptop. How can I get this in local server? Is it possible to run it locally?

**Comment by zeldaroot** [comment]
Hello.
Most likely you will not be able to run on a laptop. Take any VPS server (Debian 10 x64, Ubuntu 18 x64) and ask your hosting support to provide you with a test period.
