### ISSUE TITLE
adding movies

### ISSUE THREAD

**Issue by warnax25** [CinemaPress/CinemaPress#31]
hello
, please tell me movies like are being added, the time of addition is displayed, but the number in the database does not increase.
I made the settings as advised without restrictions. what could be the problem? thank you very much in advance

![image](https://user-images.githubusercontent.com/93061035/139141998-667b1225-1686-4d08-8643-846749e52dcd.png)

![image](https://user-images.githubusercontent.com/93061035/139142256-1351d3a3-d651-448d-8489-8f180b14f2db.png)

**Comment by Gagik39** [comment]
Здравствуйте я не покупал ключ для добавления всех фильмов Можно ли его употреблять сегодня

**Comment by zeldaroot** [comment]
Hello @Gagik39, please use English and look at this [solved issue](https://github.com/CinemaPress/CinemaPress/issues/22), it shows how to add and update movies in CinemaPress.
