### ISSUE TITLE
Please provide options to add embed links

### ISSUE THREAD

**Issue by bunty19** [CinemaPress/CinemaPress#33]
Not able to add embed video links to player. Please add options to add links of movies and episodes as some video storage providers do not have api.

**Comment by zeldaroot** [comment]
If this is a TV series, please add each embed episode through a custom field. 

<img width="559" alt="githubusercontent" src="https://user-images.githubusercontent.com/56031696/139536089-35d51510-416a-4e25-b376-79044171c51a.png">

<img width="754" alt="githubusercontent" src="https://user-images.githubusercontent.com/56031696/139536432-ff12857d-d117-45c1-841b-88a98d57daf8.png">

If this is a movie from the same source, then you can add it to the player field. 

<img width="578" alt="githubusercontent" src="https://user-images.githubusercontent.com/56031696/139536468-15069c27-6940-4026-80b2-979beabbcdbb.png">

<img width="747" alt="githubusercontent" src="https://user-images.githubusercontent.com/56031696/139536474-98f96a8e-e0a0-4a76-bb6e-f03a7c1b903f.png">

If this is a movie from several sources, add it through the custom field.

<img width="559" alt="githubusercontent" src="https://user-images.githubusercontent.com/56031696/139536487-a4327a7d-6337-4004-8d15-4d5dc6df67dd.png">

<img width="556" alt="githubusercontent" src="https://user-images.githubusercontent.com/56031696/139536490-7efa7703-011c-410e-a89f-68db4ee68093.png">

<img width="754" alt="githubusercontent" src="https://user-images.githubusercontent.com/56031696/139536498-0754c804-3364-4929-aef4-869aca895b30.png">

If you need to delete one of the players, set this field to «`none`».

<img width="557" alt="githubusercontent" src="https://user-images.githubusercontent.com/56031696/139536514-f5f427fd-c8d9-4ee9-ac47-dec2279813b9.png">

<img width="751" alt="githubusercontent" src="https://user-images.githubusercontent.com/56031696/139536519-54965a32-0855-4e74-95af-cc7c153fc512.png">

**Comment by bunty19** [comment]
Thank you for a detailed explanation

**Comment by Thecrystals** [comment]
There is a way to make it semi automatic I mean that I have a source from other website an I want to embed all movies & series from this website how I well do
