### ISSUE TITLE
Can we add addition language in player?

### ISSUE THREAD

**Issue by bunty19** [CinemaPress/CinemaPress#34]
If I have uploaded a movie or series in English can I upload additional videos in different languages like German, French then the user can select a language from the player and watch videos

**Comment by zeldaroot** [comment]
Hello, please use the name of the tabs as the language.

![image](https://user-images.githubusercontent.com/56031696/139610444-0116a261-99e5-4abe-ab2e-17f5a8a6ba50.png)

![image](https://user-images.githubusercontent.com/56031696/139610546-a3ebfdc4-3133-4afc-90cb-18d07ef89827.png)

![image](https://user-images.githubusercontent.com/56031696/139610628-df8ffdc3-8f64-4b6d-b78d-84f70a15fb4b.png)

**Comment by bunty19** [comment]
Is it possible to automate the process by uploading folder with language name to the API supported video storage

**Comment by zeldaroot** [comment]
Sure, you need to have 2 video hosting accounts and upload movies in Italian in one, and in Spanish in the second.

`1 ~ https://ita.com/api ~ result.files ~ [url] <> result.folders <> fld_id <> "https://ita.com/api?fld_id=_VALUE_" ~ file_code <> custom.player1 <> <> <> "ITA https://ita.com/e/_VALUE_" ~ title <> custom.season ~ title <> custom.episode ~ additional_info.name <> custom.imdb_id`

`1 ~ https://esp.com/api ~ result.files ~ [url] <> result.folders <> fld_id <> "https://esp.com/api?fld_id=_VALUE_" ~ file_code <> custom.player2 <> <> <> "ESP https://esp.com/e/_VALUE_" ~ title <> custom.season ~ title <> custom.episode ~ additional_info.name <> custom.imdb_id`

It is best of course to upload subtitles in these languages to the main video player.

**Comment by bunty19** [comment]
Thank you. I will use the subtitle for now
