### ISSUE TITLE
Debian 10 - OS Not Supported?

### ISSUE THREAD

**Issue by asheroto** [CinemaPress/CinemaPress#4]
I ran the script on a new Debian 10 server but got an OS Not Supported message

![image](https://user-images.githubusercontent.com/49938263/88949007-454f4780-d258-11ea-84ba-616d21e60a7d.png)

**Comment by erdometo** [comment]
At line 37 of cinemapress.sh change "*-release" to the file that includes your os id. In my case it was os-release. Now It looks like this. 
CP_OS="`awk '/^ID=/' /etc/os-release | awk -F'=' '{ print tolower($2) }'`"

Or you can simply write CP_OS="debian"

In my case, There was 2 files ending with -release and one file included an id value of my VM provider. So it was getting 2 id values seperated by a newline, which wasn't a match to "debian". Script can be improved by a loop that checks output of "awk '/^ID=/' /etc/*-release" to the desired os names.

**Comment by extensionsapp** [comment]
> I ran the script on a new Debian 10 server but got an OS Not Supported message

Please try again.

`bash <(wget cinemapress.sh -qO-)`
