### ISSUE TITLE
Creating it is successful but the site itself does not work at all.

### ISSUE THREAD

**Issue by atmos-o** [CinemaPress/CinemaPress#7]
I installed it through terminal - trying to https://cinemapress.sh/ fails with "incorrect IP or password" But both are correct.

I get this when trying to view the website. Admin panel doesn't show up either. ![image](https://user-images.githubusercontent.com/44858581/114295890-17392d00-9aa0-11eb-86e8-f4d764160464.png)

**Comment by zeldaroot** [comment]
Please, install via terminal: https://github.com/CinemaPress/CinemaPress#install-via-terminal
