### ISSUE TITLE
After installing successfully the website seems broken.

### ISSUE THREAD

**Issue by atmos-o** [CinemaPress/CinemaPress#8]
I installed it through terminal - trying to https://cinemapress.sh/ fails with "incorrect IP or password" But both are correct.

I get this when trying to view the website. Admin panel doesn't show up either. ![image](https://user-images.githubusercontent.com/44858581/114295890-17392d00-9aa0-11eb-86e8-f4d764160464.png)

**Comment by Alken123** [comment]
Same here the css does not load other wise the website is working fine i guess

**Comment by zeldaroot** [comment]
Please, install via terminal: https://github.com/CinemaPress/CinemaPress#install-via-terminal

**Comment by atmos-o** [comment]
> I installed it through terminal 

I did. It failed.

**Comment by Alken123** [comment]
Thanks It works

**Comment by atmos-o** [comment]
> Thanks It works
@Alken123 can I get some screenshots of how your one looks?

**Comment by GreenArrowlol** [comment]
> > Thanks It works
> 
> @Alken123 can I get some screenshots of how your one looks?

did you ever get it solved? I'm facing the same issue

**Comment by AlkenD** [comment]
> > > Thanks It works
> > 
> > 
> > @Alken123 can I get some screenshots of how your one looks?
> 
> did you ever get it solved? I'm facing the same issue

I suggest u find something else which is maintained i gave up on it long back
