### ISSUE TITLE
Can't access the web page

### ISSUE THREAD

**Issue by zedreez** [CinemaPress/CinemaPress#9]
Recently I install this on my new linux container in proxmox at my local server.
 Installed using the terminal method. When it ask for IP / Hostname I typed the local IP address of the linux container. Installation is success, the docker is running when I check on htop, but I can't access the web page

![image](https://user-images.githubusercontent.com/40015425/115229734-97652f80-a13d-11eb-9c0d-f81111def9cf.png)

**Comment by zeldaroot** [comment]
Running Docker containers: `docker ps`

Please see command: `cinemapress log`

**Comment by zedreez** [comment]
well, I got this when i tried to run the docker images.
![image](https://user-images.githubusercontent.com/40015425/115394037-92bb7c80-a20c-11eb-8a50-a91e8175848b.png)

**Comment by zeldaroot** [comment]
Please install on a VPS.
